aloha-agilex:
  file_path: "embodiments/aloha-agilex/"

piper:
  file_path: "embodiments/piper"

franka-panda:
  file_path: "embodiments/franka-panda/"

ARX-X5:
  file_path: "embodiments/ARX-X5"

ur5-wsg:
  file_path: "embodiments/ur5-wsg"

ur5-wsg-bimanual-static:
  file_path: "embodiments/ur5-wsg-bimanual-static"
